# Generated by Django 5.0 on 2023-12-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_registration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_registration_date',
            field=models.DateTimeField(),
        ),
    ]
